### ISSUE TITLE
Be less strict

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-publish#17]
```
$ opam publish submit git.1.4.5
[ERROR] In /Users/thomas/git/ocaml-git/git.1.4.5/opam:
  - Fields 'depends' and 'depopts' refer to the same package names

[1.4.5.tar.gz] Downloading https://github.com/mirage/ocaml-git/archive/1.4.5.tar.gz
[ERROR] Please correct the above errors and retry
```

That's actually an error in `opam lint`, not in my package, but I have no way to work-around it. Would be nice to at least add an option to not try to lint anything (`--force` or `--do-not-lint`).

**Comment by AltGr** [comment]
This has just been fixed in OPAM a few days ago, now there are two levels, errors and warnings (forgot to push the corresponding patch to opam-publish though, doing so now*).

Otherwise, here is the secret bypass: set OPAMPUBLISHBYPASSCHECKS=1
Maybe adding the results of lint to the PR message would be a good idea.

(*) branch opam-master, to be used with opam-lib master
